name:                winery
version:             "0.1.1"
github:              "fumieval/winery"
license:             BSD3
author:              "Fumiaki Kinoshita"
maintainer:          "fumiexcel@gmail.com"
copyright:           "Copyright (c) 2017 Fumiaki Kinoshita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Sustainable serialisation library
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fumieval/winery#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- cpu
- hashable
- unordered-containers
- transformers
- mtl
- prettyprinter
- prettyprinter-ansi-terminal
- text
- vector

library:
  source-dirs: src
  ghc-options: -Wall -O2
  exposed-modules:
    - Data.Winery
    - Data.Winery.Term
    - Data.Winery.Internal
    - Data.Winery.Query

executables:
  winery:
    source-dirs: app
    main: Main.hs
    dependencies:
      - winery
      - megaparsec

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - winery

benchmarks:
  bench-winery:
    source-dirs: benchmarks
    main: bench.hs
    ghc-options: -O2
    dependencies:
    - deepseq
    - gauge
    - cassava
    - binary
    - serialise
    - winery
